[build]
  command = "pip install -r requirements.txt && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.126.0"

[context.branch-deploy]
  command = "pip install -r requirements.txt && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
  command = "pip install -r requirements.txt && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.production]
[context.production.environment]
  HUGO_ENV = "production"
